DROP TABLE IF EXISTS car;
DROP TABLE IF EXISTS car_drivers;
DROP TABLE IF EXISTS driver;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS insurances;
DROP TABLE IF EXISTS claims;


CREATE TABLE driver
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document              VARCHAR NOT NULL,
    birthdate             DATE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE car
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model                 VARCHAR NOT NULL,
    manufacturer          VARCHAR NOT NULL,
    car_year              VARCHAR NOT NULL,
    fipe_value            FLOAT NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE customer
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name                  VARCHAR NOT NULL,
    driver_id             BIGINT references driver(id),
    PRIMARY KEY (id)
);


CREATE TABLE car_driver
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    is_main_driver        BOOLEAN NOT NULL,
    driver_id             BIGINT references driver(id),
    car_id                BIGINT references car(id),
    PRIMARY KEY (id)
);


CREATE TABLE claim
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_date            DATE NOT NULL,
    driver_id             BIGINT references driver(id),
    car_id                BIGINT references car(id),
    PRIMARY KEY (id)
);


CREATE TABLE insurance
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    is_active           BOOLEAN NOT NULL,
    creation_dt         TIMESTAMP NOT NULL,
    updated_dt          TIMESTAMP NULL,
    car_id              BIGINT references car(id),
    customer_id         BIGINT references customer(id),
    PRIMARY KEY (id)
);